@port = 8080
# @host = https://dnr-test.fly.dev
@host = http://localhost:{{port}}
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ2YmJmNmRmLWUxMzctNGRkYy04Mzk1LWQ4NmZiMjRlZjdkYyIsImVtYWlsIjoiZG5yQG1haWwuY29tIiwibmFtZSI6IkRpZW5lciIsImlhdCI6MTY2NTY5OTUyMiwiZXhwIjoxNjY1Nzg1OTIyfQ.7wPhiQbZbhfzHstRvQnizQ3mJLf1j2rjmlbqoFYz5iI
@id = 8603c4a2-542c-44ed-ade9-9e13dc87634f

GET {{host}}/tasks HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


###
POST {{host}}/tasks HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Task 3",
  "date": "2021-07-01",
  "hour": "12:00"
}



### Update

PUT {{host}}/tasks/{{id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
