@port = 8080
# @host = https://dnr-test.fly.dev
@host = http://localhost:{{port}}
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU4MTMyNjgwLTg3MjAtNDk1MS1hOTZlLWRiYTdlNzZlZTFkMSIsImVtYWlsIjoiZG5yQG1haWwuY29tIiwibmFtZSI6IkRpZW5lciIsImlhdCI6MTY2ODIyNjA2NywiZXhwIjoxNjY4MzEyNDY3fQ.3NyUXfCwXWJ3ul5mEwCxj1xQgWN2g_d23sOrcovnvtM
@id = 9b5d733c-edb1-4004-88e9-feb11b47de0b

GET {{host}}/tasks HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


###
POST {{host}}/tasks HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Task 3",
  "date": "2021-03-04",
  "hour": "10:04"
}



### Update
PUT {{host}}/tasks/{{id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Task Update1"
}

### Delete
DELETE {{host}}/tasks/76ed6d51-c24c-4dcd-af9c-d607de25bb93 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


### Get with query
GET {{host}}/tasks/search/?title=Grow HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
