@port = 3000
@host = http://localhost:{{port}}
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVhZWQyNjU0LTZmNDMtNDQ5Yi1hZTQ2LWY5YjFlMGVkNjlkZiIsImVtYWlsIjoiZGllbmVyQGdtYWlsLmNvbSIsIm5hbWUiOiJEaWVuZXIiLCJpYXQiOjE2NjUwNzk3NDMsImV4cCI6MTY2NTE2NjE0M30.amSzMIqQgiej0XMao9XyhDTsf0g1r6USr8lAc5LFBJw
@id = eaa5aacc-cba4-49cb-8300-fa6a9165e5f0

GET {{host}}/tasks HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


###
POST {{host}}/tasks HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Task 3",
  "description": "Task 3 description"
}



### Update

PUT {{host}}/tasks/{{id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "status": "DONE"
}
