@port = 8080
# @host = https://dnr-test.fly.dev
@host = http://localhost:{{port}}
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNjZTNjMmVhLTM3MTgtNGM4Ny04NDA5LWJmMzU2NzQwNmUzOSIsImVtYWlsIjoibWFpbEBtYWlsLmNvbSIsIm5hbWUiOiJVc2VyIG5hbWUiLCJpYXQiOjE2NjU2MTQ4MTUsImV4cCI6MTY2NTcwMTIxNX0.wlh3Kkc580C4wnPFzx3eEP0fnDKqNlil7PIrbHgidcs


POST {{host}}/users HTTP/1.1
Content-Type: application/json

{
  "name": "Diener",
  "email": "dnr@mail.com",
  "password": "123Qw",
  "password_confirm": "123Qw"
}


### unauthorized
GET {{host}}/users HTTP/1.1


### Login user
POST {{host}}/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "dnr@mail.com",
  "password": "123Qw"
}

### get user
GET {{host}}/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
