@port = 3000
@host = http://localhost:{{port}}
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVhZWQyNjU0LTZmNDMtNDQ5Yi1hZTQ2LWY5YjFlMGVkNjlkZiIsImVtYWlsIjoiZGllbmVyQGdtYWlsLmNvbSIsIm5hbWUiOiJEaWVuZXIiLCJpYXQiOjE2NjUwNzk3NDMsImV4cCI6MTY2NTE2NjE0M30.amSzMIqQgiej0XMao9XyhDTsf0g1r6USr8lAc5LFBJw

POST {{host}}/users HTTP/1.1
Content-Type: application/json

{
  "name": "Diener",
  "email": "diener@gmail.com",
  "password": "123456",
  "password_confirm": "123456"
}


###

GET {{host}}/users HTTP/1.1


### Login

POST {{host}}/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "diener@gmail.com",
  "password": "123456"
}

###

GET {{host}}/users/tasks HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
